services:
  - type: web
    name: starship-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: MSG91_AUTH_KEY
        sync: false
      - key: MSG91_SENDER_ID
        sync: false
      - key: MSG91_TEMPLATE_ID
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
